name = "Hugo Void"
license = "MIT"
licenselink = "https://github.com/xxLYNX/hugo-void/blob/main/LICENSE"
description = "A clean, minimalistic theme for Hugo with a focus on readability and simplicity"

homepage = "https://github.com/xxLYNX/hugo-void"

tags = ["blog", "minimalist", "responsive", "tailwind", "clean", "light", "personal", "dark"]
features = ["responsive", "tailwind css", "minimalist", "blog", "clean design", "fast", "seo-friendly"]

[author]
    name = "Connor Kelley"
    homepage = "https://github.com/xxLYNX" 